<a href="https://colab.research.google.com/github/Jlia-miy/-/blob/main/3_Pandas_(%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# импорт библиотеки
import pandas as pd
import numpy as np  # numpy часто используется вместе с Pandas

# Задание 1. Создание DataFrame

Создайте DataFrame из следующего списка данных:

In [1]:
data = {
    'Имя': ['Степан', 'Инна', 'Алексей', 'Мария'],
    'Возраст': [25, 30, 22, 29],
    'Город': ['Москва', 'Казань', 'Москва', 'Новосибирск']
}

# продолжите здесь

Выведите информацию о DataFrame (тип данных, количество строк и столбцов).

In [5]:
df = pd.DataFrame(data)
df

       Имя  Возраст        Город
0   Степан       25       Москва
1     Инна       30       Казань
2  Алексей       22       Москва
3    Мария       29  Новосибирск

# Задание 2. Основные операции с DataFrame

Используя DataFrame из задания 1, выполните следующие операции:

Добавьте новый столбец "Зарплата" с данными [50000, 60000, 55000, 65000].

In [7]:
df['Зарплата'] = [50000, 60000, 55000, 65000]
df

       Имя  Возраст        Город  Зарплата
0   Степан       25       Москва     50000
1     Инна       30       Казань     60000
2  Алексей       22       Москва     55000
3    Мария       29  Новосибирск     65000

Найдите средний возраст всех людей в DataFrame.

In [8]:
df['Возраст'].mean()

np.float64(26.5)

Отфильтруйте всех людей, чей возраст больше 25 лет.

In [13]:
df_1= df[df['Возраст']>25]
df_1

     Имя  Возраст        Город  Зарплата
1   Инна       30       Казань     60000
3  Мария       29  Новосибирск     65000

# Задание 3. Индексация и фильтрация

Используя DataFrame из задания 1:

Выберите только строки, где город — "Москва".

In [14]:
df_2 = df[df['Город']=='Москва']
df_2

       Имя  Возраст   Город  Зарплата
0   Степан       25  Москва     50000
2  Алексей       22  Москва     55000

Используя loc, отфильтруйте людей, у которых зарплата больше 55000.

In [30]:
df_3 = df[df.loc[:]['Зарплата']>55000]
df_3

     Имя  Возраст        Город  Зарплата
1   Инна       30       Казань     60000
3  Мария       29  Новосибирск     65000

# Задание 4. Группировка данных

Создайте DataFrame с информацией о продажах магазина:

In [33]:
sales_data = {
    'Дата': ['2026-02-01', '2026-02-01', '2026-02-02', '2026-02-02'],
    'Магазин': ['Магазин 1', 'Магазин 2', 'Магазин 1', 'Магазин 2'],
    'Продажи': [120, 150, 130, 180]
}

# продолжите здесь
salies = pd.DataFrame(sales_data)
salies

         Дата    Магазин  Продажи
0  2026-02-01  Магазин 1      120
1  2026-02-01  Магазин 2      150
2  2026-02-02  Магазин 1      130
3  2026-02-02  Магазин 2      180

Найдите общую сумму продаж для каждого магазина.

In [37]:
salies.groupby('Магазин')['Продажи'].sum()

Магазин
Магазин 1    250
Магазин 2    330
Name: Продажи, dtype: int64

# Задание 5. Работа с пропущенными значениями

Создайте DataFrame с пропущенными значениями:

In [38]:
data_with_na = {
    'Имя': ['Петр', 'Евгения', 'Алексей', None],
    'Возраст': [25, None, 22, 29],
    'Город': ['Москва', 'Казань', 'Москва', 'Новосибирск']
}
new_data = pd.DataFrame(data_with_na)
new_data
# продолжите здесь

       Имя  Возраст        Город
0     Петр     25.0       Москва
1  Евгения      NaN       Казань
2  Алексей     22.0       Москва
3     None     29.0  Новосибирск

Найдите количество пропущенных значений в каждом столбце.

In [39]:
new_data.isnull().sum()

Имя        1
Возраст    1
Город      0
dtype: int64

Заполните пропущенные значения в столбце "Возраст" средним значением.

In [41]:
new_data['Возраст'].fillna(new_data['Возраст'].mean(), inplace=True)
new_data

/tmp/ipython-input-6151/534404263.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  new_data['Возраст'].fillna(new_data['Возраст'].mean(), inplace=True)

       Имя    Возраст        Город
0     Петр  25.000000       Москва
1  Евгения  25.333333       Казань
2  Алексей  22.000000       Москва
3     None  29.000000  Новосибирск

# Задание 6. Слияние и объединение DataFrame

Используя два DataFrame:

In [42]:
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Имя': ['Степан', 'Инна', 'Алексей']
})

df2 = pd.DataFrame({
    'ID': [2, 3, 4],
    'Город': ['Москва', 'Казань', 'Новосибирск']
})

In [43]:
df1

   ID      Имя
0   1   Степан
1   2     Инна
2   3  Алексей

In [44]:
df2

   ID        Город
0   2       Москва
1   3       Казань
2   4  Новосибирск

Объедините два DataFrame по столбцу "ID".

In [45]:
df1.merge(df2[['ID', 'Город']], on='ID')

   ID      Имя   Город
0   2     Инна  Москва
1   3  Алексей  Казань

Выполните слияние по внешнему ключу (outer join).

In [52]:
df1.merge(df2[['ID', 'Город']], how='outer')

   ID      Имя        Город
0   1   Степан          NaN
1   2     Инна       Москва
2   3  Алексей       Казань
3   4      NaN  Новосибирск

# Задание 7. Работа с датами

Создайте DataFrame с датами:

In [53]:
date_data = {
    'Дата': pd.to_datetime(['2026-02-01', '2026-02-02', '2026-02-03']),
    'Событие': ['Событие 1', 'Событие 2', 'Событие 3']
}
event = pd.DataFrame(date_data)
event
# продолжите здесь

        Дата    Событие
0 2026-02-01  Событие 1
1 2026-02-02  Событие 2
2 2026-02-03  Событие 3

Найдите максимальную и минимальную дату.

In [55]:
min(event['Дата'])

Timestamp('2026-02-01 00:00:00')

In [57]:
max(event['Дата'])

Timestamp('2026-02-03 00:00:00')

Добавьте столбец с днем недели для каждой даты.

In [62]:
event['Неделя'] = event['Дата'].dt.dayofweek+1
event

        Дата    Событие  Неделя
0 2026-02-01  Событие 1       7
1 2026-02-02  Событие 2       1
2 2026-02-03  Событие 3       2

# Задание 8. Сортировка данных

Создайте DataFrame с информацией о студентах:

In [63]:
students = {
    'Имя': ['Степан', 'Мария', 'Алексей', 'Ирина'],
    'Баллы': [80, 90, 70, 85],
    'Возраст': [22, 30, 25, 27]
}
student = pd.DataFrame(students)
student
# продолжите здесь

       Имя  Баллы  Возраст
0   Степан     80       22
1    Мария     90       30
2  Алексей     70       25
3    Ирина     85       27

Отсортируйте DataFrame по баллам в порядке убывания.

In [67]:
student.sort_values(by='Баллы', ascending=False)

       Имя  Баллы  Возраст
1    Мария     90       30
3    Ирина     85       27
0   Степан     80       22
2  Алексей     70       25

Отсортируйте DataFrame по возрасту и баллам одновременно.

In [69]:
student.sort_values(by=['Баллы', 'Возраст'], ascending=[True, False])

       Имя  Баллы  Возраст
2  Алексей     70       25
0   Степан     80       22
3    Ирина     85       27
1    Мария     90       30

# Задание 9. Загрузка и выгрузка данных

Загрузите csv-файл (например, 'titanic.csv') из временного хранилища Colab

In [6]:
import pandas as pd
import numpy as np  # numpy часто используется вместе с Pandas
df_tit = pd.read_csv('titanic.csv')
df_tit.head(7)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S

Загрузите csv-файл (например, 'titanic.csv') с вашего Диска

In [12]:
path = "/content/titanic.csv"
df = pd.read_csv(path)
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

Загрузите csv-файл (например, 'titanic.csv') с вашего компьютера

In [14]:
from google.colab import files
uploaded = files.upload()

KeyboardInterrupt:

Загрузите файл Excel с вашего компьютера

Выгрузите данные, полученные в одном из заданий выше, в csv-файл